Market/Controllers/AdministrativaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Market.Models;
using Market.Services;
using Market.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace Market.Controllers
{
  
    public class AdministrativaController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdministrativaController(ApplicationDbContext db)
        {
            _db = db;
        }

        [Authorize]
        public IActionResult Index()
        {            
            var nome = HttpContext.User.Claims.FirstOrDefault(u => u.Type == ClaimTypes.Name).Value;
            ViewBag.Nome = nome;

            ObterContadores();

            return View();        

        }

        public IActionResult CadastroCliente()
        {
            return View();
        }        

        [HttpPost]
        public IActionResult CadastroCliente(ViewModelCadastro Cad)
        {            
            var endereco = new Endereco { Cep = Cad.Endereco.Cep, Bairro = Cad.Endereco.Bairro, Rua = Cad.Endereco.Rua, Numero = Cad.Endereco.Numero, Cidade = Cad.Endereco.Cidade, Complemento = Cad.Endereco.Complemento };
            _db.Enderecos.Add(endereco);

            var cadastro = new Usuario
            {
                Nome = Cad.Cadastro.Nome,
                Email = Cad.Cadastro.Email,
                Cpf = Cad.Cadastro.Cpf.Replace(".", "").Replace("-", ""),
                DataNascimento = Cad.Cadastro.DataNascimento,
                Password = HashService.Crip(Cad.Cadastro.Cpf.Replace(".", "").Replace("-", "")),
                Telefone = Cad.Cadastro.Telefone,
                Celular = Cad.Cadastro.Celular,
                Sexo = Cad.Cadastro.Sexo,
                TipoDeUsuarioId = 3,
                EnderecoId = endereco.IdEndereco,
                Status = true
            };

            _db.Cadastros.Add(cadastro);

            if (ModelState.IsValid)
            {
                _db.SaveChanges();
            }

            return RedirectToAction("CadastroCliente");
        }

        public void ObterContadores() {
            ViewBag.Produtos = 0;
            ViewBag.Usuarios = 0;
            ViewBag.NotasFicais = 0;
            ViewBag.Pedidos = 0;
        }

    }
}

Market/Views/Administrativa/AddInsumo.cshtml
@model IEnumerable<Market.Models.Insumo>

@{
    ViewData["Title"] = "AddInsumo";
    Layout = "~/Views/Shared/_LayoutAdministrativa.cshtml";
}
<script>

</script>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Cadastrar Insumo</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form asp-controller="Administrativa" asp-action="AddInsumo">
        <div class="box-body">

            <div class="col-lg-4">
                <label for="Nome">Nome</label>
                <input type="text" class="form-control" placeholder="Nome do produto" name="Nome">
            </div>
            <div class="col-lg-4">
                <label for="Quantidade">Quantidade</label>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Quantidade em Kg" name="Quantidade">
                    <span class="input-group-addon">Kg</span>
                </div>
            </div>
            <div class="col-lg-4">
                <label for="Valor">Valor</label>
                <div class="input-group">
                    <span class="input-group-addon">R$</span>
                    <input type="text" class="form-control" placeholder="Valor do Kg" name="Valor">
                </div>
            </div>

        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-info pull-right">Adicionar</button>
        </div>
        <!-- /.box-footer -->
    </form>
</div>



<div class="box">
    <div class="box-header">
        <h3 class="box-title">Insumos</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">
        <table class="table table-hover">
            <tbody>
                <tr>
                    <th style="width: 35%">
                        @Html.DisplayName("Nome")
                    </th>
                    <th style="width: 15%">
                        @Html.DisplayName("Preço em R$")
                    </th>
                    <th style="width: 15%">
                        @Html.DisplayName("Quantidade em Kg")
                    </th>
                    <th style="width: 25%; text-align: center">
                        @Html.DisplayName("Estoque")
                    </th>

                    <th style="width: 10%; text-align: center">
                        @Html.DisplayName("Editar")
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PrecoInsumo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantidade)
                        </td>

                        <td>

                            @{
                                double porcentagem = Math.Round((item.Quantidade / item.EstoqueMax) * 100, 1);

                                var color = "";
                                var bg = "";
                                string porc = porcentagem.ToString().Replace(",", ".");

                                if (porcentagem < 25)
                                {
                                    color = "progress-bar progress-bar-danger";
                                    bg = "badge bg-red";

                                }
                                if (porcentagem >= 25 && porcentagem < 50)
                                {
                                    color = "progress-bar progress-bar-yellow";
                                    bg = "badge bg-yellow";
                                }
                                if (porcentagem >= 50 && porcentagem <= 100)
                                {
                                    color = "progress-bar progress-bar-success";
                                    bg = "badge bg-green";
                                }
                                <div class="form-group">
                                    <div class="col-lg-9">
                                        <div class="progress progress-xs progress-striped active">
                                            <div class="@color" style="width: @porc%"></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <span class="@bg">@porcentagem%</span>
                                    </div>
                                </div>
                            }

                        </td>
                        <td style="text-align: center">
                            <a asp-action="RemoveInsumo" asp-route-id="@item.IdInsumo" class="glyphicon glyphicon-trash fa-lg"></a>
                            <a>&emsp;</a>
                            <a href="#" data-toggle="modal" data-target="#modal-edit" class="glyphicon glyphicon-edit fa-lg editInsumo"
                               rel="@item.Nome|@item.Quantidade|@item.IdInsumo|@item.Nome">
                            </a>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
</div>


<!-- /.modal EDIT-->
<div class="modal fade" id="modal-edit">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                
                    <h4 class="modal-title">Editar Insumo</h4>
               
            </div>
            <form asp-controller="Administrativa" asp-action="EditInsumo">
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label>Nome</label>
                        <input id="EditNome" class="form-control" name="EditNome" />
                    </div>
                    <div class="form-group">
                        <label>Quantidade Atual</label>
                        <input id="EditQuantidade" class="form-control" name="EditQuantidade" disabled />
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-8">
                                <label>Quantidade Modificada</label>
                                <input id="EditQuantidade" class="form-control" name="EditQuantidade" />
                            </div>
                            <div class="col-lg-4">
                                <label>Selecione opção</label>
                                <div class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-success">
                                        <input type="radio" name="option" value="adicionar" autocomplete="off">Adicionar
                                    </label>
                                    <label class="btn btn-danger">
                                        <input type="radio" name="option" value="remover" autocomplete="off">Remover
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">

                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                    <button class="btn btn-primary" name="EditId" id="EditId">Salvar</button>

                </div>
            </form>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal EDIT-->

Market/Views/Administrativa/CadastroCliente.cshtml
@model Market.ViewModels.ViewModelCadastro

@{
    ViewData["Title"] = "CadastroCliente";
    Layout = "~/Views/Shared/_LayoutAdministrativa.cshtml";
}

<script src="~/Script/CEP.js"></script>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Cadastro de clientes</h3>
    </div>
    <form asp-action="CadastroCliente" class="form-horizontal">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="col-sm-4">
                    <label asp-for="Cadastro.Nome" class="control-label"></label>
                    <input asp-for="Cadastro.Nome" class="form-control" required/>
                    <span asp-validation-for="Cadastro.Nome" class="text-danger"></span>
                </div>

                <div class="col-sm-4">
                    <label asp-for="Cadastro.Email" class="control-label"></label>
                    <input asp-for="Cadastro.Email" class="form-control" required/>
                    <span asp-validation-for="Cadastro.Email" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Cadastro.Cpf" class="control-label"></label>
                    <input asp-for="Cadastro.Cpf" class="form-control" placeholder="Ex.: 000.000.000-00" onkeypress="CEP(this, '###.###.###-##')" maxlength="14" required>
                    <span asp-validation-for="Cadastro.Cpf" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-3">
                    <label asp-for="Cadastro.DataNascimento" class="control-label"></label>
                    <input asp-for="Cadastro.DataNascimento" class="form-control" type="date" required>
                    <span asp-validation-for="Cadastro.DataNascimento" class="text-danger"></span>
                </div>

                <div class="col-sm-3">
                    <label asp-for="Cadastro.Telefone" class="control-label"></label>
                    <input asp-for="Cadastro.Telefone" class="form-control" placeholder="Ex.: (00) 0000-0000" onkeyup="TEL( this, mtel );" maxlength="14" />
                    <span asp-validation-for="Cadastro.Telefone" class="text-danger"></span>
                </div>

                <div class="col-sm-3">
                    <label asp-for="Cadastro.Celular" class="control-label"></label>
                    <input asp-for="Cadastro.Celular" class="form-control" placeholder="Ex.: (00) 00000-0000" onkeyup="CEL( this, mcel );" maxlength="15" />
                    <span asp-validation-for="Cadastro.Celular" class="text-danger"></span>
                </div>

                <div class="col-sm-3">
                    <label asp-for="Cadastro.Sexo" class="control-label"></label>
                    <select asp-for="Cadastro.Sexo" class="form-control select2" style="width: 100%;">
                        <option value="0">Selecione</option>
                        <option>Masculino</option>
                        <option>Feminino</option>
                    </select>

                    @*<input  class="form-control" />*@
                    <span asp-validation-for="Cadastro.Sexo" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4">
                    <label asp-for="Endereco.Cep" class="control-label"></label>
                    <input asp-for="Endereco.Cep" class="form-control" placeholder="Ex.: 00000-000" id="cep" onblur="pesquisacep(this.value);" onkeypress="CEP(this, '#####-###')" maxlength="9" />
                    <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                </div>

                <div class="col-sm-6">
                    <label asp-for="Endereco.Rua" class="control-label"></label>
                    <input asp-for="Endereco.Rua" class="form-control" id="rua" />
                    <span asp-validation-for="Endereco.Rua" class="text-danger"></span>
                </div>
                <div class="col-sm-2">
                    <label asp-for="Endereco.Numero" class="control-label"></label>
                    <input asp-for="Endereco.Numero" class="form-control" />
                    <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4">
                    <label asp-for="Endereco.Cidade" class="control-label"></label>
                    <input asp-for="Endereco.Cidade" class="form-control" id="cidade" />
                    <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Endereco.Bairro" class="control-label"></label>
                    <input asp-for="Endereco.Bairro" class="form-control" id="bairro" />
                    <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Endereco.Complemento" class="control-label"></label>
                    <input asp-for="Endereco.Complemento" class="form-control" />
                    <span asp-validation-for="Endereco.Complemento" class="text-danger"></span>
                </div>
            </div>

            <div class="box-footer">
                <button type="submit" value="Create" class="btn btn-info pull-right">Cadastrar</button>
            </div>
        </div>

    </form>
</div>

Market/Views/Administrativa/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>